### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by brianc** [thumblemonks/riot#50]
Riot was the very first project I ever contributed to on github.  You & alex were really friendly and helpful even though I was a total noob and didn't know what I was doing _at all_.  

Just wanted to say thanks a ton for your patience and kindness back in the day.  I've mostly stopped using ruby now, but I saw a news item for this repo pop up in my feed & just wanted to let you know you guys are great.

**Comment by gus** [comment]
Love to close 5 year old issues :)
